mixed-port: 7890
redir-port: 9797
tproxy-port: 9898
ipv6: true
mode: "rule"
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: "silent"
bind-address: "*"
find-process-mode: "always"
external-controller: "0.0.0.0:9090"
external-ui: "./dashboard"
geo-auto-update: true
geo-update-interval: 24
geodata-mode: true
geox-url:
  geoip: "https://v6.gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://v6.gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://v6.gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"
  asn: "https://v6.gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
secret: ""
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, "8080-8880"]
    TLS:
      ports: [443, 5228, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain: ["+.v2ex.com"]
  skip-domain: ["Mijia Cloud"]
tun:
  enable: true
  device: "Meta"
  stack: "gvisor"
  dns-hijack: ["any:53", "tcp://any:53"]
  udp-timeout: 300
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
  exclude-package: []
dns:
  enable: true
  ipv6: true
  enhanced-mode: "fake-ip"
  fake-ip-range: "198.18.0.1/16"
  use-hosts: true
  use-system-hosts: true
  respect-rules: true
  cache-algorithm: "arc"
  default-nameserver:
    - "tls://223.5.5.5"
    - "tls://223.6.6.6"
    - "tls://119.29.29.29"
    - "tls://1.12.12.12"
  nameserver:
    - "https://cloudflare-dns.com/dns-query"
    - "https://dns.google/dns-query"
    - "https://dns.quad9.net/dns-query"
    - "https://dns.opendns.com/dns-query"
  proxy-server-nameserver:
    - "https://dns.alidns.com/dns-query"
    - "https://doh.pub/dns-query"
    - "https://doh.360.cn/dns-query"
  direct-nameserver:
    - "https://dns.alidns.com/dns-query"
    - "https://doh.pub/dns-query"
    - "https://doh.360.cn/dns-query"
  fake-ip-filter-mode: "blacklist"
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "*.localhost"
    - "*.home.arpa"
    - "geosite:private"
    - "geosite:category-ntp"
