/*
 * Auto-generated from config/ACL4SSR_mod_mini.ini
 * Generated by scripts/gen-flclash-scripts.js
 */
function main(config) {
  const generatedProxyGroups = [
  {
    "name": "🚀 节点选择",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png",
    "proxies": [
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他",
      "DIRECT"
    ]
  },
  {
    "name": "🥇 手动选择1",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available.png",
    "include-all": true,
    "filter": ".*"
  },
  {
    "name": "🥈 手动选择2",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available.png",
    "include-all": true,
    "filter": ".*"
  },
  {
    "name": "ᯅ QUEST",
    "type": "select",
    "proxies": [
      "🇺🇲 ‍美国自动",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2"
    ],
    "include-all": true,
    "filter": ".*"
  },
  {
    "name": "Ⓜ️ 微软云盘",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/OneDrive.png",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "Ⓜ️ 微软服务",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "🎬 EMBY",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "DIRECT",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "🕸 刮削",
    "type": "select",
    "proxies": [
      "🔮 负载均衡 no🇯🇵",
      "🚀 节点选择",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "🕸 刮削🇯🇵",
    "type": "select",
    "proxies": [
      "🇯🇵 日本自动"
    ],
    "include-all": true,
    "filter": "🇯🇵(?!.*[🇦-🇿]{2})"
  },
  {
    "name": "📲 电报消息",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png",
    "proxies": [
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他",
      "DIRECT"
    ]
  },
  {
    "name": "📢 谷歌FCM",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "🤖 GPT",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png",
    "proxies": [
      "🇺🇲 ‍美国自动",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🎏 ‍其他",
      "DIRECT"
    ]
  },
  {
    "name": "👨‍💻 GitHub",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png",
    "proxies": [
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "🌍 国外媒体",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/ForeignMedia.png",
    "proxies": [
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他",
      "DIRECT"
    ]
  },
  {
    "name": "📺 哔哩哔哩港澳台",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/BiliBili.png",
    "proxies": [
      "🇨🇳 ‍中国自动",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇸🇬 狮城自动",
      "🎏 ‍其他",
      "DIRECT",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡"
    ]
  },
  {
    "name": "🛑 广告拦截",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png",
    "proxies": [
      "REJECT",
      "DIRECT"
    ]
  },
  {
    "name": "🎯 全球直连",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡"
    ]
  },
  {
    "name": "🐟 Final兜底",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "♻️ 自动选择",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png",
    "include-all": true,
    "filter": ".*",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  },
  {
    "name": "🔯 故障转移",
    "type": "fallback",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available.png",
    "include-all": true,
    "filter": ".*",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  },
  {
    "name": "🔮 负载均衡",
    "type": "load-balance",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png",
    "include-all": true,
    "filter": ".*",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  },
  {
    "name": "🔮 负载均衡 no🇯🇵",
    "type": "load-balance",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png",
    "include-all": true,
    "filter": "(?!.*(日本|JP|Japan|🇯🇵)).*",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  },
  {
    "name": "🇭🇰 香港自动",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",
    "include-all": true,
    "filter": "🇭🇰(?!.*(?!🇨🇳)[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  },
  {
    "name": "🇹🇼 台湾自动",
    "type": "url-test",
    "include-all": true,
    "filter": "🇹🇼(?!.*(?!🇨🇳)[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  },
  {
    "name": "🇨🇳 ‍中国自动",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/China.png",
    "include-all": true,
    "filter": "(🇭🇰|🇹🇼|🇨🇳|🇲🇴)(?!.*[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  },
  {
    "name": "🇸🇬 狮城自动",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",
    "include-all": true,
    "filter": "🇸🇬(?!.*[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  },
  {
    "name": "🇯🇵 日本自动",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",
    "include-all": true,
    "filter": "🇯🇵(?!.*[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  },
  {
    "name": "🇺🇲 ‍美国自动",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",
    "include-all": true,
    "filter": "(🇺🇸|🇺🇲)(?!.*[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  },
  {
    "name": "🎏 ‍其他",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png",
    "include-all": true,
    "filter": "^(?!.*(🇨🇳|🇭🇰|🇲🇴|🇹🇼|🇸🇬|🇯🇵|🇺🇸|🇺🇲)(?!.*[🇦-🇿]{2}))",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 300,
    "tolerance": 50
  }
];
  const generatedRuleProviders = {
  "proxy_custom": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/proxy-custom.list",
    "path": "./ruleset/proxy_custom.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "PT": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/PT.list",
    "path": "./ruleset/PT.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "direct_custom": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/direct-custom.list",
    "path": "./ruleset/direct_custom.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "ProxyMedia": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/ProxyMedia.list",
    "path": "./ruleset/ProxyMedia.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "scraper_nojp": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/scraper-nojp.list",
    "path": "./ruleset/scraper_nojp.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "scraper_jp": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/scraper-jp.list",
    "path": "./ruleset/scraper_jp.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "DMM": {
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DMM/DMM.yaml",
    "path": "./ruleset/DMM.yaml",
    "behavior": "classical",
    "interval": 86400,
    "format": "yaml",
    "type": "http"
  },
  "AI": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/AI.list",
    "path": "./ruleset/AI.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "BilibiliHMT": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list",
    "path": "./ruleset/BilibiliHMT.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "Emby": {
    "url": "https://raw.githubusercontent.com/cutethotw/ClashRule/main/Rule/Emby.yaml",
    "path": "./ruleset/Emby.yaml",
    "behavior": "classical",
    "interval": 86400,
    "format": "yaml",
    "type": "http"
  },
  "Emby_2": {
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Emby/Emby.yaml",
    "path": "./ruleset/Emby_2.yaml",
    "behavior": "classical",
    "interval": 86400,
    "format": "yaml",
    "type": "http"
  },
  "AddEmbyList": {
    "url": "https://raw.githubusercontent.com/Nowat995/emby/main/AddEmbyList.list",
    "path": "./ruleset/AddEmbyList.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "GitHub": {
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml",
    "path": "./ruleset/GitHub.yaml",
    "behavior": "classical",
    "interval": 86400,
    "format": "yaml",
    "type": "http"
  },
  "quest3": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/quest3.list",
    "path": "./ruleset/quest3.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "OpenAI": {
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml",
    "path": "./ruleset/OpenAI.yaml",
    "behavior": "classical",
    "interval": 86400,
    "format": "yaml",
    "type": "http"
  },
  "Telegram": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list",
    "path": "./ruleset/Telegram.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "OneDrive": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list",
    "path": "./ruleset/OneDrive.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "Microsoft": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list",
    "path": "./ruleset/Microsoft.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "GoogleFCM": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list",
    "path": "./ruleset/GoogleFCM.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "BanAD": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list",
    "path": "./ruleset/BanAD.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "BanProgramAD": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list",
    "path": "./ruleset/BanProgramAD.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "ProxyGFWlist": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list",
    "path": "./ruleset/ProxyGFWlist.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "applications": {
    "url": "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt",
    "path": "./ruleset/applications.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "LocalAreaNetwork": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list",
    "path": "./ruleset/LocalAreaNetwork.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "UnBan": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list",
    "path": "./ruleset/UnBan.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "GoogleCN": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list",
    "path": "./ruleset/GoogleCN.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "SteamCN": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list",
    "path": "./ruleset/SteamCN.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "ChinaIp": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list",
    "path": "./ruleset/ChinaIp.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "ChinaDomain": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list",
    "path": "./ruleset/ChinaDomain.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "ChinaCompanyIp": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list",
    "path": "./ruleset/ChinaCompanyIp.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "Download": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list",
    "path": "./ruleset/Download.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  }
};
  const generatedRules = [
  "RULE-SET,proxy_custom,🚀 节点选择",
  "RULE-SET,PT,🎯 全球直连",
  "RULE-SET,direct_custom,🎯 全球直连",
  "RULE-SET,ProxyMedia,🌍 国外媒体",
  "RULE-SET,scraper_nojp,🕸 刮削",
  "RULE-SET,scraper_jp,🕸 刮削🇯🇵",
  "RULE-SET,DMM,🕸 刮削🇯🇵",
  "RULE-SET,AI,🤖 GPT",
  "RULE-SET,BilibiliHMT,📺 哔哩哔哩港澳台",
  "RULE-SET,Emby,🎬 EMBY",
  "RULE-SET,Emby_2,🎬 EMBY",
  "RULE-SET,AddEmbyList,🎬 EMBY",
  "RULE-SET,GitHub,👨‍💻 GitHub",
  "RULE-SET,quest3,ᯅ QUEST",
  "RULE-SET,OpenAI,🤖 GPT",
  "RULE-SET,Telegram,📲 电报消息",
  "RULE-SET,OneDrive,Ⓜ️ 微软云盘",
  "RULE-SET,Microsoft,Ⓜ️ 微软服务",
  "RULE-SET,GoogleFCM,📢 谷歌FCM",
  "RULE-SET,BanAD,🛑 广告拦截",
  "RULE-SET,BanProgramAD,🛑 广告拦截",
  "RULE-SET,ProxyGFWlist,🚀 节点选择",
  "RULE-SET,applications,🎯 全球直连",
  "RULE-SET,LocalAreaNetwork,🎯 全球直连",
  "RULE-SET,UnBan,🎯 全球直连",
  "RULE-SET,GoogleCN,🎯 全球直连",
  "RULE-SET,SteamCN,🎯 全球直连",
  "RULE-SET,ChinaIp,🎯 全球直连",
  "RULE-SET,ChinaDomain,🎯 全球直连",
  "RULE-SET,ChinaCompanyIp,🎯 全球直连",
  "RULE-SET,Download,🎯 全球直连",
  "GEOIP,LAN,🎯 全球直连",
  "GEOIP,CN,🎯 全球直连",
  "MATCH,🐟 Final兜底"
];

  config["proxy-groups"] = generatedProxyGroups;
  config["rule-providers"] = generatedRuleProviders;
  config["rules"] = generatedRules;

  return config;
}
