/*
 * Auto-generated from config/Home_mod_mini.ini
 * Generated by scripts/gen-flclash-scripts.js
 */
function main(config) {
  const generatedProxyGroups = [
  {
    "name": "🚀 节点选择",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png",
    "proxies": [
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他",
      "DIRECT"
    ]
  },
  {
    "name": "🥇 手动选择1",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available.png",
    "include-all": true,
    "filter": ".*"
  },
  {
    "name": "🥈 手动选择2",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available.png",
    "include-all": true,
    "filter": ".*"
  },
  {
    "name": "🏠 回家",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Home.png",
    "proxies": [
      "DIRECT"
    ],
    "include-all": true,
    "filter": "^(?!.*(((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev))))).*(?i)Home"
  },
  {
    "name": "ᯅ QUEST",
    "type": "select",
    "proxies": [
      "🇺🇲 ‍美国自动",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2"
    ],
    "include-all": true,
    "filter": "^(?!.*(((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev))))).*$"
  },
  {
    "name": "Ⓜ️ 微软云盘",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/OneDrive.png",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "Ⓜ️ 微软服务",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Microsoft.png",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "🎬 EMBY",
    "type": "select",
    "proxies": [
      "🚀 节点选择",
      "DIRECT",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "🕸 刮削",
    "type": "select",
    "proxies": [
      "🔮 负载均衡 no🇯🇵",
      "🚀 节点选择",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "🕸 刮削🇯🇵",
    "type": "select",
    "proxies": [
      "🇯🇵 日本自动"
    ],
    "include-all": true,
    "filter": "^(?!.*(((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev))))).*🇯🇵(?!.*[🇦-🇿]{2})"
  },
  {
    "name": "📲 电报消息",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png",
    "proxies": [
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他",
      "DIRECT"
    ]
  },
  {
    "name": "📢 谷歌FCM",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Google_Search.png",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "🤖 AI",
    "type": "select",
    "proxies": [
      "🇺🇲 ‍美国自动",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🎏 ‍其他",
      "DIRECT"
    ]
  },
  {
    "name": "👨‍💻 GitHub",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/GitHub.png",
    "proxies": [
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "🌍 国外媒体",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/ForeignMedia.png",
    "proxies": [
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他",
      "DIRECT"
    ]
  },
  {
    "name": "📺 哔哩哔哩港澳台",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/BiliBili.png",
    "proxies": [
      "🇨🇳 ‍中国自动",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇸🇬 狮城自动",
      "🎏 ‍其他",
      "DIRECT",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡"
    ]
  },
  {
    "name": "🛑 广告拦截",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png",
    "proxies": [
      "REJECT",
      "DIRECT"
    ]
  },
  {
    "name": "🎯 全球直连",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡"
    ]
  },
  {
    "name": "🐟 Final兜底",
    "type": "select",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Final.png",
    "proxies": [
      "DIRECT",
      "🚀 节点选择",
      "🥇 手动选择1",
      "🥈 手动选择2",
      "♻️ 自动选择",
      "🔯 故障转移",
      "🔮 负载均衡",
      "🇭🇰 香港自动",
      "🇹🇼 台湾自动",
      "🇨🇳 ‍中国自动",
      "🇸🇬 狮城自动",
      "🇯🇵 日本自动",
      "🇺🇲 ‍美国自动",
      "🎏 ‍其他"
    ]
  },
  {
    "name": "♻️ 自动选择",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Auto.png",
    "include-all": true,
    "filter": "^(?!.*(((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev))))).*$",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 600,
    "tolerance": 50
  },
  {
    "name": "🔯 故障转移",
    "type": "fallback",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available.png",
    "include-all": true,
    "filter": "^(?!.*((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev)))).*$",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 600,
    "tolerance": 50
  },
  {
    "name": "🔮 负载均衡",
    "type": "load-balance",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png",
    "include-all": true,
    "filter": "^(?!.*((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev)))).*$",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 600,
    "tolerance": 50
  },
  {
    "name": "🔮 负载均衡 no🇯🇵",
    "type": "load-balance",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Speedtest.png",
    "include-all": true,
    "filter": "^(?!.*(日本|JP|Japan|🇯🇵))(?!.*((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev)))).*$",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 600,
    "tolerance": 50
  },
  {
    "name": "🇭🇰 香港自动",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png",
    "include-all": true,
    "filter": "^(?!.*(((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev))))).*🇭🇰(?!.*(?!🇨🇳)[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 600,
    "tolerance": 50
  },
  {
    "name": "🇹🇼 台湾自动",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png",
    "include-all": true,
    "filter": "^(?!.*(((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev))))).*🇹🇼(?!.*(?!🇨🇳)[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 600,
    "tolerance": 50
  },
  {
    "name": "🇨🇳 ‍中国自动",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/China.png",
    "include-all": true,
    "filter": "^(?!.*(((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev))))).*(🇭🇰|🇹🇼|🇨🇳|🇲🇴)(?!.*[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 600,
    "tolerance": 50
  },
  {
    "name": "🇸🇬 狮城自动",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png",
    "include-all": true,
    "filter": "^(?!.*(((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev))))).*🇸🇬(?!.*[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 600,
    "tolerance": 50
  },
  {
    "name": "🇯🇵 日本自动",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png",
    "include-all": true,
    "filter": "^(?!.*(((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev))))).*🇯🇵(?!.*[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 600,
    "tolerance": 50
  },
  {
    "name": "🇺🇲 ‍美国自动",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png",
    "include-all": true,
    "filter": "^(?!.*(((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev))))).*(🇺🇸|🇺🇲)(?!.*[🇦-🇿]{2})",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 600,
    "tolerance": 50
  },
  {
    "name": "🎏 ‍其他",
    "type": "url-test",
    "icon": "https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png",
    "include-all": true,
    "filter": "^(?!.*(((?i)GB|Traffic|Expire|Premium|频道|订阅|ISP|流量|到期|重置|用户|官网|Data Left|Remain:|Traffic:|Expir[ey]|(\\d[\\d.]*\\s*[MG]B[^\\dA-Za-z]+|[:：]\\s*)\\d[\\d.]*\\s*GB(?![\\dA-Za-z])|流量|剩[余餘]|[到过過效]期|重置|Reset|リセット|域名|机场|官网|本站|计划|面板|到期|套餐|更多|关注|购买|QQ|测试|(?:https?:\\/\\/[^\\s]+|www\\.[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}|[a-zA-Z0-9-]+\\.(com|net|org|io|cn|xyz|me|top|site|online|tech|dev)))))(?!.*(🇨🇳|🇭🇰|🇲🇴|🇹🇼|🇸🇬|🇯🇵|🇺🇸|🇺🇲)(?!.*[🇦-🇿]{2}))",
    "url": "http://www.gstatic.com/generate_204",
    "interval": 600,
    "tolerance": 50
  }
];
  const generatedRuleProviders = {
  "LocalAreaNetwork": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list",
    "path": "./ruleset/LocalAreaNetwork.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "home_lan": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/home-lan.list",
    "path": "./ruleset/home_lan.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "proxy_custom": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/proxy-custom.list",
    "path": "./ruleset/proxy_custom.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "pt": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/pt.list",
    "path": "./ruleset/pt.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "direct_custom": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/direct-custom.list",
    "path": "./ruleset/direct_custom.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "BilibiliHMT": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list",
    "path": "./ruleset/BilibiliHMT.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "androidcn_allow": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/androidcn-allow.list",
    "path": "./ruleset/androidcn_allow.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "proxy_media": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/proxy-media.list",
    "path": "./ruleset/proxy_media.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "scraper_nojp": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/scraper-nojp.list",
    "path": "./ruleset/scraper_nojp.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "scraper_jp": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/scraper-jp.list",
    "path": "./ruleset/scraper_jp.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "DMM": {
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DMM/DMM.yaml",
    "path": "./ruleset/DMM.yaml",
    "behavior": "classical",
    "interval": 86400,
    "format": "yaml",
    "type": "http"
  },
  "ai": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/ai.list",
    "path": "./ruleset/ai.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "OpenAI": {
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml",
    "path": "./ruleset/OpenAI.yaml",
    "behavior": "classical",
    "interval": 86400,
    "format": "yaml",
    "type": "http"
  },
  "GitHub": {
    "url": "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml",
    "path": "./ruleset/GitHub.yaml",
    "behavior": "classical",
    "interval": 86400,
    "format": "yaml",
    "type": "http"
  },
  "quest3": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/quest3.list",
    "path": "./ruleset/quest3.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "Telegram": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list",
    "path": "./ruleset/Telegram.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "OneDrive": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list",
    "path": "./ruleset/OneDrive.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "Microsoft": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list",
    "path": "./ruleset/Microsoft.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "GoogleFCM": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list",
    "path": "./ruleset/GoogleFCM.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "android_block": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/android-block.list",
    "path": "./ruleset/android_block.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "app_mutated": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/app-mutated.list",
    "path": "./ruleset/app_mutated.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "game_mutated": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/game-mutated.list",
    "path": "./ruleset/game_mutated.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "adblock_reject": {
    "url": "https://raw.githubusercontent.com/wuyaos/OpenClash-Rules/main/rules/adblock-reject.list",
    "path": "./ruleset/adblock_reject.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "BanAD": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list",
    "path": "./ruleset/BanAD.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "BanProgramAD": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list",
    "path": "./ruleset/BanProgramAD.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "BanEasyList": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list",
    "path": "./ruleset/BanEasyList.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "BanEasyListChina": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list",
    "path": "./ruleset/BanEasyListChina.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "BanEasyPrivacy": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list",
    "path": "./ruleset/BanEasyPrivacy.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "ProxyGFWlist": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list",
    "path": "./ruleset/ProxyGFWlist.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "applications": {
    "url": "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt",
    "path": "./ruleset/applications.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "UnBan": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list",
    "path": "./ruleset/UnBan.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "GoogleCN": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list",
    "path": "./ruleset/GoogleCN.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "SteamCN": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list",
    "path": "./ruleset/SteamCN.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "ChinaIp": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list",
    "path": "./ruleset/ChinaIp.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "ChinaDomain": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list",
    "path": "./ruleset/ChinaDomain.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "ChinaCompanyIp": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list",
    "path": "./ruleset/ChinaCompanyIp.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  },
  "Download": {
    "url": "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list",
    "path": "./ruleset/Download.list",
    "behavior": "classical",
    "interval": 86400,
    "format": "text",
    "type": "http"
  }
};
  const generatedRules = [
  "RULE-SET,LocalAreaNetwork,🎯 全球直连",
  "RULE-SET,home_lan,🏠 回家",
  "RULE-SET,proxy_custom,🚀 节点选择",
  "RULE-SET,pt,🎯 全球直连",
  "RULE-SET,direct_custom,🎯 全球直连",
  "RULE-SET,BilibiliHMT,📺 哔哩哔哩港澳台",
  "RULE-SET,androidcn_allow,🎯 全球直连",
  "RULE-SET,proxy_media,🌍 国外媒体",
  "RULE-SET,scraper_nojp,🕸 刮削",
  "RULE-SET,scraper_jp,🕸 刮削🇯🇵",
  "RULE-SET,DMM,🕸 刮削🇯🇵",
  "RULE-SET,ai,🤖 AI",
  "RULE-SET,OpenAI,🤖 AI",
  "RULE-SET,GitHub,👨‍💻 GitHub",
  "RULE-SET,quest3,ᯅ QUEST",
  "RULE-SET,Telegram,📲 电报消息",
  "RULE-SET,OneDrive,Ⓜ️ 微软云盘",
  "RULE-SET,Microsoft,Ⓜ️ 微软服务",
  "RULE-SET,GoogleFCM,📢 谷歌FCM",
  "RULE-SET,android_block,🛑 广告拦截",
  "RULE-SET,app_mutated,🎯 全球直连",
  "RULE-SET,game_mutated,🎯 全球直连",
  "RULE-SET,adblock_reject,🛑 广告拦截",
  "RULE-SET,BanAD,🛑 广告拦截",
  "RULE-SET,BanProgramAD,🛑 广告拦截",
  "RULE-SET,BanEasyList,🛑 广告拦截",
  "RULE-SET,BanEasyListChina,🛑 广告拦截",
  "RULE-SET,BanEasyPrivacy,🛑 广告拦截",
  "RULE-SET,ProxyGFWlist,🚀 节点选择",
  "RULE-SET,applications,🎯 全球直连",
  "RULE-SET,UnBan,🎯 全球直连",
  "RULE-SET,GoogleCN,🎯 全球直连",
  "RULE-SET,SteamCN,🎯 全球直连",
  "RULE-SET,ChinaIp,🎯 全球直连",
  "RULE-SET,ChinaDomain,🎯 全球直连",
  "RULE-SET,ChinaCompanyIp,🎯 全球直连",
  "RULE-SET,Download,🎯 全球直连",
  "GEOIP,CN,🎯 全球直连",
  "MATCH,🐟 Final兜底"
];

  config["proxy-groups"] = generatedProxyGroups;
  config["rule-providers"] = generatedRuleProviders;
  config["rules"] = generatedRules;

  return config;
}
